fixed some error

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -28,16 +28,19 @@ before_script:
     if [[ -z "$ENVIRONMENT" ]]; then
        echo "ENVIRONMENT is not set"
        exit 1
-    elif [[ "$ENVIRONMENT" == "develop" ]]; then
+    elif [[ "$ENVIRONMENT" == "Develop" ]]; then
        export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID_DEV
        export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY_DEV
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV 
+       export ENVIRONMENT_NAME=$DEVELOP_ENVIRONMENT_NAME
     elif [[ "$ENVIRONMENT" == "Production" ]]; then
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD 
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD    
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
+       export ENVIRONMENT_NAME=$PRODUCTION_ENVIRONMENT_NAME 
     else
-       echo " environment not found!...."
+       echo "environment not found!"
+       exit 1
     fi      
 
     
